Style update to yellow
flyteorg/flyteConsoleSrc pull request #7
Opened 2022-11-17 16:18 UTC by james-union

Signed-off-by: James <james@union.ai>

2022-11-17 16:22 UTC, ursucarina requested changes
waiting for confirmation this doesn't break flyteconsole

2022-11-17 16:22 UTC, ursucarina commented on packages/console/src/components/Theme/constants.ts
> +export const primaryDarkColor = COLOR_SPECTRUM.yellow70.color;
@james-union can you check this against the flyteconsole repo in carina/final? does this change the color scheme for console?

2022-11-17 16:23 UTC, james-union commented on packages/console/src/components/Theme/constants.ts
> +export const primaryDarkColor = COLOR_SPECTRUM.yellow70.color;
yes. it changes to flyteconsole. If it shouldn't affect to flyteconsole, does it mean that we should get color theme from env variables?

2022-11-18 17:28 UTC, jsonporter approved these changes

2022-11-18 17:28 UTC, merged